move from PICO_RP2350 to PICO_RP2350A as used in sdk
2350 now compiles but fails to link..

Linking build/ch.elf
/opt/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /tmp/ch.elf.35ZNmy.ltrans0.ltrans.o:(.rodata.cmd_sequence.0+0x14): undefined reference to `_crt0_c1_entry'
collect2: error: ld returned 1 exit status
make: *** [../../../os/common/startup/ARMCMx/compilers/GCC/mk/rules.mk:222: build/ch.elf] Error 1