define PICO_RP2350 AND PICO_RP2350A as the former is used to decide if were gonna use PICO_USE_SW_SPIN_LOCKS, and we should on the RP2350 "due tp errata"
see top of
/home/buzz2/Chibi/pico-sdk/src/rp2_common/hardware_sync_spin_lock/include/hardware/sync/spin_lock.h

and then after we get this, fixed in next commit via changing -mcpu
/home/buzz2/Chibi/pico-sdk/src/rp2_common/hardware_sync_spin_lock/include/hardware/sync/spin_lock.h:152:2: error: #error no SW_SPIN_TRY_LOCK available for PICO_USE_SW_SPIN_LOCK on this platform
  152 | #error no SW_SPIN_TRY_LOCK available for PICO_USE_SW_SPIN_LOCK on this platform